export const CRYPTO_STORE = "crypto";
export const SEARCH_STORE = "search";
export const APP_STORE = "app";

export const CRYPTO_DATA = "CRYPTO_DATA";
export const EXCHANGE_DATA = "EXCHANGE_DATA";
export const CRYPTO_PORTFOLIO = "CRYPTO_PORTFOLIO";
export const SHOW_LOADING = "SHOW_LOADING";
export const SEARCH_TERM = "SEARCH_TERM";
export const CRYPTO_SEARCH_RESULT = "CRYPTO_SEARCH_RESULT";

export const CRYPTO_VALUES = "CRYPTO_VALUES";
export const EXCHANGE_VALUES = "EXCHANGE_VALUES";
export const CRYPTO_PORTFOLIO_FULL_DATA = "CRYPTO_PORTFOLIO_FULL_DATA";

export const SET_SHOW_LOADING = "SET_SHOW_LOADING";
export const FETCH_CRYPTO_CURRENCIES = "FETCH_CRYPTO_CURRENCIES";
export const SET_CRYPTO_CURRENCY_VALUES = "SET_CRYPTO_CURRENCY_VALUES";
export const FETCH_EXCHANGES = "FETCH_EXCHANGES";
export const SET_EXCHANGE_VALUES = "SET_EXCHANGE_VALUES";
export const ADD_TO_PORTFOLIO = "ADD_TO_PORTFOLIO";
export const UPDATE_PORTFOLIO = "UPDATE_PORTFOLIO";
export const REMOVE_FROM_PORTFOLIO = "REMOVE_FROM_PORTFOLIO";
export const CHECK_LOCAL_STORAGE_PORTFOLIO = "CHECK_LOCAL_STORAGE_PORTFOLIO";
export const SET_SEARCH_TERM = "SET_SEARCH_TERM";
export const CLEAR_SEARCH_TERM = "CLEAR_SEARCH_TERM";
export const REDIRECT_TO_PATH = "REDIRECT_TO_PATH";

export const UPDATE_SEARCH_TERM = "UPDATE_SEARCH_TERM";
export const UPDATE_SEARCH_RESULT = "UPDATE_SEARCH_RESULT";